apiVersion: v1
kind: Pod
metadata:
  labels:
    example: logging-sidecar
  name: logging-sidecar-fluentd
spec:
  containers:
  - name: logger
    image: ubuntu:14.04
    command: ["bash", "-c", "i=\"0\"; while true; do echo \"`hostname`: $i \" >> /var/log/hostname.log; date --rfc-3339 ns >> /var/log/date.log; sleep 60; i=$[$i+1]; done"]
    volumeMounts:
    - name: log-storage
      mountPath: /var/log
  - name: logger-sidecar
    image: gcr.io/google_containers/fluentd-sidecar-es:1.0
    env:
    - name: FILES_TO_COLLECT
      value: "/mnt/log/hostname.log /mnt/log/date.log"
    volumeMounts:
    - name: log-storage
      readOnly: true
      mountPath: /mnt/log
  volumes:
  - name: log-storage
    emptyDir: {}
